/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as LeakDetectionRouteImport } from './routes/leak-detection'
import { Route as HeatMapRouteImport } from './routes/heat-map'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiPredictionRouteImport } from './routes/ai-prediction'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LeakDetectionRoute = LeakDetectionRouteImport.update({
  id: '/leak-detection',
  path: '/leak-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatMapRoute = HeatMapRouteImport.update({
  id: '/heat-map',
  path: '/heat-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPredictionRoute = AiPredictionRouteImport.update({
  id: '/ai-prediction',
  path: '/ai-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-prediction': typeof AiPredictionRoute
  '/analytics': typeof AnalyticsRoute
  '/heat-map': typeof HeatMapRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-prediction': typeof AiPredictionRoute
  '/analytics': typeof AnalyticsRoute
  '/heat-map': typeof HeatMapRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-prediction': typeof AiPredictionRoute
  '/analytics': typeof AnalyticsRoute
  '/heat-map': typeof HeatMapRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-prediction'
    | '/analytics'
    | '/heat-map'
    | '/leak-detection'
    | '/live-monitoring'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-prediction'
    | '/analytics'
    | '/heat-map'
    | '/leak-detection'
    | '/live-monitoring'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/ai-prediction'
    | '/analytics'
    | '/heat-map'
    | '/leak-detection'
    | '/live-monitoring'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPredictionRoute: typeof AiPredictionRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HeatMapRoute: typeof HeatMapRoute
  LeakDetectionRoute: typeof LeakDetectionRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leak-detection': {
      id: '/leak-detection'
      path: '/leak-detection'
      fullPath: '/leak-detection'
      preLoaderRoute: typeof LeakDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat-map': {
      id: '/heat-map'
      path: '/heat-map'
      fullPath: '/heat-map'
      preLoaderRoute: typeof HeatMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-prediction': {
      id: '/ai-prediction'
      path: '/ai-prediction'
      fullPath: '/ai-prediction'
      preLoaderRoute: typeof AiPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPredictionRoute: AiPredictionRoute,
  AnalyticsRoute: AnalyticsRoute,
  HeatMapRoute: HeatMapRoute,
  LeakDetectionRoute: LeakDetectionRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
